### ISSUE TITLE
Create contributing.md

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#354] opened 2024-10-17 16:00 UTC
Anthony gave a lot of guidelines on how to contribute on this PR: https://github.com/numerique-gouv/impress/pull/340
It's be great to formalize that into a CONTRIBUTING.md file at the root of the repo that we reference to people who start making prs.

**Comment by AntoLC** [comment] 2024-10-17 18:16
Duplicate of this one: #342

**Closed** 2024-10-18 07:33 UTC
Labels: documentation, duplicate, good first issue
